[package]
name = "omprs-gdk"
version = "0.1.0"
edition = "2021"

[dependencies]
omprs-codegen = {path="../omprs-codegen"}
windows = { version = "0.52.0", features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
] }
paste = "1.0"
